# Generated by Django 5.2.1 on 2025-06-17 21:58

import applications.core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ejemplo: Arriendo, Luz, Agua, Internet, Insumos médicos, etc.', max_length=100, unique=True, verbose_name='Nombre del Tipo de Gasto')),
                ('descripcion', models.TextField(blank=True, help_text='Detalle adicional sobre este tipo de gasto (opcional).', null=True, verbose_name='Descripción del Gasto')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este tipo de gasto está disponible para ser seleccionado.', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Gasto',
                'verbose_name_plural': 'Tipos de Gastos',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='duracion_cita',
        ),
        migrations.AddField(
            model_name='doctor',
            name='duracion_atencion',
            field=models.PositiveIntegerField(default=30, help_text='Tiempo estándar asignado a cada paciente.', verbose_name='Duración de Cita (minutos)'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='core/medicamentos/', verbose_name='Foto del Medicamento'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='curriculum',
            field=models.FileField(blank=True, help_text='Archivo PDF o DOC (opcional).', null=True, upload_to='core/curriculums/', verbose_name='Currículum Vitae'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='firma_digital',
            field=models.ImageField(blank=True, help_text='Imagen que será usada para firmar digitalmente.', null=True, upload_to='core/firmas/', verbose_name='Firma Digital'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='core/doctores/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='imagen_receta',
            field=models.ImageField(blank=True, help_text='Encabezado o firma que se mostrará en recetas médicas.', null=True, upload_to='core/recetas/', verbose_name='Imagen para Recetas'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='core/empleados/', verbose_name='Foto del Empleado'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del paciente (opcional).', null=True, upload_to='core/pacientes/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='masculino', max_length=10, verbose_name='Sexo'),
        ),
        migrations.CreateModel(
            name='FotoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen relacionada con el paciente. Puede ser histórica o actual.', upload_to=applications.core.models.ruta_foto_paciente, verbose_name='Imagen del Paciente')),
                ('descripcion', models.TextField(blank=True, help_text='Comentario opcional sobre la imagen (ej. cicatriz, antes/después, etc.)', null=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que se subió la imagen.', verbose_name='Fecha de Subida')),
                ('paciente', models.ForeignKey(help_text='Paciente al que pertenece esta imagen.', on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Foto del Paciente',
                'verbose_name_plural': 'Fotos de los Pacientes',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='GastoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se incurrió el gasto.', verbose_name='Fecha del Gasto')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Monto en dólares del gasto realizado.', max_digits=10, verbose_name='Valor del Gasto')),
                ('observacion', models.TextField(blank=True, help_text='Comentario adicional sobre este gasto (opcional).', null=True, verbose_name='Observación')),
                ('tipo_gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_mensuales', to='core.tipogasto', verbose_name='Tipo de Gasto')),
            ],
            options={
                'verbose_name': 'Gasto Mensual',
                'verbose_name_plural': 'Gastos Mensuales',
                'ordering': ['-fecha'],
            },
        ),
    ]
