# Generated by Django 5.2.1 on 2025-06-17 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepago',
            name='aplica_seguro',
            field=models.BooleanField(default=False, help_text='Marca si el servicio tiene cobertura por seguro médico.', verbose_name='Aplica Seguro'),
        ),
        migrations.AddField(
            model_name='detallepago',
            name='descripcion_seguro',
            field=models.CharField(blank=True, help_text='Nombre del seguro utilizado. Ejemplo: Saludsa Nivel 2.', max_length=255, null=True, verbose_name='Descripción del Seguro'),
        ),
        migrations.AddField(
            model_name='detallepago',
            name='valor_seguro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor real cubierto por el seguro. Se usará en lugar del precio normal si se aplica seguro.', max_digits=10, null=True, verbose_name='Valor Cubierto por Seguro'),
        ),
        migrations.AlterField(
            model_name='detallepago',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad del servicio facturado (ej. 1 examen, 2 procedimientos, etc.).', verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detallepago',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado sobre el precio base. Ejemplo: 10 para 10%.', max_digits=5, verbose_name='Descuento %'),
        ),
        migrations.AlterField(
            model_name='detallepago',
            name='pago',
            field=models.ForeignKey(help_text='Pago al que corresponde este detalle de cobro.', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='doctor.pago', verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='detallepago',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, help_text='Precio normal por unidad del servicio, sin considerar seguros.', max_digits=10, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='detallepago',
            name='servicio_adicional',
            field=models.ForeignKey(help_text='Servicio adicional cobrado (ej. Radiografía, Laboratorio).', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pago', to='doctor.serviciosadicionales', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='detallepago',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Subtotal calculado automáticamente, considerando seguro y descuento.', max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='evidencia_pago',
            field=models.ImageField(blank=True, help_text='Captura de pantalla o comprobante del pago', null=True, upload_to='doctor/evidencia_pagos/', verbose_name='Evidencia de Pago'),
        ),
    ]
