# Generated by Django 5.2.1 on 2025-06-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_detallepago_aplica_seguro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='doctor',
        ),
        migrations.AlterUniqueTogether(
            name='citamedica',
            unique_together={('fecha', 'hora_cita')},
        ),
        migrations.AlterUniqueTogether(
            name='horarioatencion',
            unique_together={('dia_semana', 'hora_inicio', 'hora_fin')},
        ),
        migrations.RemoveField(
            model_name='citamedica',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='horarioatencion',
            name='doctor',
        ),
    ]
