# Generated by Django 5.2 on 2025-07-04 11:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_diagnosticocore_medicamentocore_pacientecore"),
        ("doctor", "0005_remove_atencion_doctor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y Hora"
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "icd_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Código CIE"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas Adicionales"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Diagnóstico (Doctor App)",
                "verbose_name_plural": "Diagnósticos (Doctor App)",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Primer_nombre",
                    models.CharField(max_length=150, verbose_name="Nombres"),
                ),
                (
                    "apellido",
                    models.CharField(max_length=150, verbose_name="Apellidos"),
                ),
                (
                    "dni",
                    models.CharField(max_length=13, unique=True, verbose_name="Cédula"),
                ),
                ("birth_date", models.DateField(verbose_name="Fecha de Nacimiento")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                        verbose_name="Género",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Dirección"
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Tipo de Sangre",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente (Doctor App)",
                "verbose_name_plural": "Pacientes (Doctor App)",
                "ordering": ["apellido", "Primer_nombre"],
            },
        ),
        migrations.RenameIndex(
            model_name="citamedica",
            new_name="idx_fecha_hora_cita",
            old_name="idx_fecha_hora",
        ),
        migrations.AlterField(
            model_name="atencion",
            name="diagnostico",
            field=models.ManyToManyField(
                blank=True,
                help_text="Diagnósticos clínicos asociados a esta atención.",
                related_name="atenciones",
                to="core.diagnostico",
                verbose_name="Diagnósticos",
            ),
        ),
        migrations.AlterField(
            model_name="atencion",
            name="fecha_atencion",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Fecha y hora en que se registró la atención.",
                verbose_name="Fecha de Atención",
            ),
        ),
        migrations.AlterField(
            model_name="citamedica",
            name="estado",
            field=models.CharField(
                choices=[
                    ("disponible", "Disponible"),
                    ("ocupado", "Ocupado"),
                    ("atendido", "Atendido"),
                ],
                max_length=20,
                verbose_name="Estado de la Cita",
            ),
        ),
        migrations.AlterField(
            model_name="detallepago",
            name="aplica_seguro",
            field=models.BooleanField(
                default=False,
                help_text="¿Servicio cubierto por seguro?",
                verbose_name="Aplica Seguro",
            ),
        ),
        migrations.AlterField(
            model_name="detallepago",
            name="cantidad",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Cantidad del servicio facturado.",
                verbose_name="Cantidad",
            ),
        ),
        migrations.AlterField(
            model_name="detallepago",
            name="descripcion_seguro",
            field=models.CharField(
                blank=True,
                help_text="Nombre del seguro utilizado.",
                max_length=255,
                null=True,
                verbose_name="Descripción del Seguro",
            ),
        ),
        migrations.AlterField(
            model_name="detallepago",
            name="descuento_porcentaje",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Descuento sobre precio base (0-100).",
                max_digits=5,
                verbose_name="Descuento %",
            ),
        ),
        migrations.AlterField(
            model_name="detallepago",
            name="precio_unitario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio por unidad del servicio.",
                max_digits=10,
                null=True,
                verbose_name="Precio Unitario",
            ),
        ),
        migrations.AlterField(
            model_name="detallepago",
            name="servicio_adicional",
            field=models.ForeignKey(
                help_text="Servicio adicional cobrado.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="detalles_pago",
                to="doctor.serviciosadicionales",
                verbose_name="Servicio",
            ),
        ),
        migrations.AlterField(
            model_name="detallepago",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                help_text="Subtotal (cantidad * precio con descuento).",
                max_digits=10,
                verbose_name="Subtotal",
            ),
        ),
        migrations.AlterField(
            model_name="detallepago",
            name="valor_seguro",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor cubierto si aplica seguro.",
                max_digits=10,
                null=True,
                verbose_name="Valor Cubierto por Seguro",
            ),
        ),
        migrations.AlterField(
            model_name="pago",
            name="monto_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Monto Total",
            ),
        ),
        migrations.AddField(
            model_name="diagnosis",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnoses_doctor_app",
                to="doctor.patient",
                verbose_name="Paciente",
            ),
        ),
    ]
